version: '3.2'
services:
  fakegree:
    image: fakegree
    build: fakegree
    restart: always
    volumes:
      - ./fakegree:/fakegree
    environment:
      IP: 192.168.50.111  # change this to a free IP in the HVAC's subnet
      PORT: 1812 # leave this
      HOSTNAME: dis.gree.com # leave this
    networks:
      dirty:
        ipv4_address: 192.168.50.111 # must match the IP above
    cap_add:
      - NET_ADMIN

networks:
  dirty:
    driver: macvlan
    driver_opts:
      parent: enpls0
    ipam:
      driver: default
      config:
       - subnet: 192.168.50.0/24
         ip_range: 192.168.50.248/29
         gateway: 192.168.50.1
