version: '3.2'
services:
  fakegree:
    image: fakegree
    build: fakegree
    restart: always
    volumes:
      - ./fakegree:/fakegree
    environment:
      IP: 192.168.50.69  # change this to a free IP in the HVAC's subnet
      PORT: 1812 # leave this
      HOSTNAME: dis.gree.com # leave this
    networks:
      dirty:
        ipv4_address: 192.168.50.69 # must match the IP above

networks:
  dirty:
    driver: macvlan
    name: dirty
    driver_opts:
      parent: enpls0
    ipam:
      driver: default
      config:
        - subnet: 192.168.50.0/24  # change this to the HVAC's subnet
          gateway: 192.168.50.1   # change this to the HVAC's subnet's gateway

